name: Build Project

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.0' # 选择你需要的 Visual Studio 版本

    - name: Build the project
      run: |
        msbuild LaserGRBL.sln /p:Configuration=Release /p:BaseOutputPath=${{ github.workspace }}\bin

    - name: Create Release Package
      run: |
        # 假设生成的文件在 bin/Release 目录下
        mkdir release
        # 将生成的文件打包成 zip 文件
        Compress-Archive -Path 'bin\*' -DestinationPath 'release\package.zip'

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }} # 你可以根据需要修改版本号
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          release/package.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
